---
theme: auto
default_2fa_method: totp
server:
  host: 0.0.0.0
  port: 9091
log:
  level: debug
  format: text
  file_path: "/logs/authelia.log"
  keep_stdout: true
totp:
  disable: false
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
webauthn:
  disable: false
  timeout: 60s
  attestation_conveyance_preference: indirect
  user_verification: preferred
authentication_backend:
  password_reset:
    disable: false
  refresh_interval: 5m
  ldap:
    implementation: custom
    timeout: 5s
    start_tls: false
    username_attribute: uid
    additional_users_dn: ou=people
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    additional_groups_dn: ou=groups
    groups_filter: "(member={dn})"
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
password_policy:
  standard:
    enabled: false
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: false
access_control:
  default_policy: two_factor
session:
  name: authelia_session
  same_site: lax
  expiration: 12h
  inactivity: 15m
  remember_me_duration: 1M
  redis:
    host: redis
    port: 6379
    database_index: 1
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  local:
    path: /config/db.sqlite3
notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
identity_providers:
  oidc:
    clients:
      - id: portainer
        description: Portainer
        secret: "$pbkdf2-sha512$310000$kpbPLLkc6UQ9hdbhsLK0Cw$47PbY1xIh/97DfpPxMT8GkfZWa3RLB2gvrnhBNRDZCtuOkCROX46jMnIQpPBVCwprmgc7rwJVmV944e/8CpYjw"
        public: false
        authorization_policy: two_factor
        redirect_uris:
          - https://portainer.home.filipmikina.com
        scopes:
          - openid
          - profile
          - groups
          - email
      - id: miniflux
        description: Miniflux RSS
        secret: "$pbkdf2-sha512$310000$gRQfIE0eWD7Ny47dsvkiTw$5G9F8vZtbIw40Nu2ljD2DSU8cZFfr8h.Mdxo09OogruCfWITyyfvGSHAYlq8yQeNPZPkEdtwR8SPyvR4JiyfQw"
        public: false
        authorization_policy: two_factor
        redirect_uris:
          - https://rss.home.filipmikina.com/oauth2/oidc/callback
        scopes:
          - openid
          - profile
          - groups
          - email
