version: "3.9"

services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - ./config:/www/assets
    networks:
      - selfhost

networks:
  selfhost:
    external: true
