services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    restart: unless-stopped
    networks:
      - selfhost
    expose:
      - 6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  selfhost:
    external: true
