---
title: "VPS dashboard"
subtitle: "Filip Mikina"

header: false
footer: false

columns: "3"
connectivityCheck: true

proxy:
  useCredentials: true

services:
  - name: "Reading"
    icon: "fas fa-book-open"
    items:
      - name: "Miniflux"
        subtitle: "RSS Reader"
        tag: "app"
        icon: "fas fa-rss"
        url: "https://rss.home.filipmikina.com"
  - name: "Notifications"
    icon: "fas fa-directions"
    items:
      - name: "Changedetection"
        subtitle: "Notify on change"
        icon: "fas fa-bell"
        url: "https://changedetection.home.filipmikina.com"
  - name: "Monitoring"
    icon: "fas fa-chart-line"
    items:
      - name: "Uptime Kuma"
        subtitle: "Uptime monitor"
        icon: "fas fa-heartbeat"
        tag: "app"
        url: "https://uptime.home.filipmikina.com"
      - name: "Doku"
        subtitle: "Disk usage"
        icon: "fas fa-save"
        tag: "app"
        url: "https://disk.home.filipmikina.com"
      - name: "Glances"
        subtitle: "Quick metrics"
        icon: "fas fa-glasses"
        tag: "app"
        url: "https://glances.home.filipmikina.com"
      - name: "Portainer"
        tag: "app"
        icon: "fab fa-docker"
        subtitle: "Containers Management"
        url: "https://portainer.home.filipmikina.com"
