---
title: "VPS dashboard"
subtitle: "Filip Mikina"

header: true
footer: false

columns: "3"
connectivityCheck: true

proxy:
  useCredentials: true

services:
  - name: "Reading"
    icon: "fas fa-book-open"
    items:
      - name: "Miniflux"
        subtitle: "RSS Reader"
        tag: "app"
        icon: "fas fa-rss"
        url: "https://rss.home.filipmikina.com"
  - name: "Monitoring"
    icon: "fas fa-chart-line"
    items:
      - name: "Glances"
        subtitle: "Quick metrics"
        icon: "fas fa-glasses"
        tag: "app"
        url: "https://glances.home.filipmikina.com"
      - name: "Portainer"
        tag: "app"
        icon: "fab fa-docker"
        subtitle: "Containers Management"
        url: "https://portainer.home.filipmikina.com"
